"""
rescrape_insufficient.py
========================
Targeted re-scraper for the 55 recipes that have 'insufficient_data' status.

WHY this script exists
----------------------
During the original scraping run, these recipes ended up with 0 % USDA
ingredient coverage — meaning either the ingredient text was garbled,
quantities were missing, or the scraper pulled incomplete data.
Re-fetching from the source URL gives us a clean ingredient list with
proper quantities, which lets the USDA matching pipeline actually work.

Strategy per source
-------------------
  food.com       → JSON-LD  (schema.org/Recipe embedded in page)
  africanbites   → WPRM CSS selectors, JSON-LD fallback
  cheflola       → WPRM CSS selectors, JSON-LD fallback
  BBC Food       → JSON-LD
  Zimbo Kitchen  → JSON-LD, WPRM fallback
  other/unknown  → JSON-LD attempt only

WHY JSON-LD as the primary strategy
------------------------------------
Modern recipe sites embed their data as <script type="application/ld+json">
blocks using the schema.org/Recipe vocabulary.  This is more reliable than
CSS selectors because it is the canonical machine-readable data the site
exposes for SEO — it rarely changes even when the page layout is redesigned.

Input
-----
  data/outputs/insufficient_data_recipes_inspection.csv
  (generated by build_inspection_csv.py — contains recipe_id + source_url)

Output
------
  data/scraped/rescraped_insufficient.csv
  columns: recipe_id, recipe_name, servings, ingredients, source_url, strategy_used

Run from african_recipes_nutrition/:
    py scrapers/rescrape_insufficient.py
"""

import csv
import json
import os
import re
import sys
import time

sys.stdout.reconfigure(encoding='utf-8')

import requests
from bs4 import BeautifulSoup

BASE         = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_FILE   = os.path.join(BASE, 'data', 'outputs', 'insufficient_data_recipes_inspection.csv')
OUTPUT_FILE  = os.path.join(BASE, 'data', 'scraped', 'rescraped_insufficient.csv')
FAILED_FILE  = os.path.join(BASE, 'scrapers', 'rescrape_failed.txt')

HEADERS = {
    'User-Agent': (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
        'AppleWebKit/537.36 (KHTML, like Gecko) '
        'Chrome/124.0.0.0 Safari/537.36'
    ),
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.9',
}

UNICODE_FRACTIONS = {
    '¼': '1/4', '½': '1/2', '¾': '3/4',
    '⅓': '1/3', '⅔': '2/3', '⅛': '1/8',
    '⅜': '3/8', '⅝': '5/8', '⅞': '7/8',
}


def normalize_fractions(text):
    for uc, asc in UNICODE_FRACTIONS.items():
        text = text.replace(uc, asc)
    return text


def classify_source(url):
    """Return a short source label based on the URL domain."""
    if 'food.com'       in url: return 'food.com'
    if 'africanbites'   in url: return 'africanbites'
    if 'cheflola'       in url: return 'cheflola'
    if 'bbc.co.uk'      in url: return 'bbc'
    if 'zimbokitchen'   in url: return 'zimbokitchen'
    return 'other'


# ── Extraction strategy 1: JSON-LD ────────────────────────────────────────────

def find_recipe_jsonld(soup):
    """
    Walk all <script type="application/ld+json"> blocks and return the first
    schema.org/Recipe object found.  Handles bare objects, lists, and @graph.
    """
    for script in soup.find_all('script', type='application/ld+json'):
        try:
            data = json.loads(script.string or '')
        except (json.JSONDecodeError, TypeError):
            continue

        candidates = []
        if isinstance(data, list):
            candidates = data
        elif isinstance(data, dict):
            candidates = data.get('@graph', [data])

        for obj in candidates:
            type_val = obj.get('@type', '')
            types = type_val if isinstance(type_val, list) else [type_val]
            if 'Recipe' in types:
                return obj
    return None


def parse_servings(yield_val):
    if isinstance(yield_val, list):
        yield_val = yield_val[0] if yield_val else ''
    m = re.search(r'\d+', str(yield_val))
    return m.group(0) if m else str(yield_val).strip()


def extract_jsonld(soup):
    """
    Pull name, servings, and ingredient list from a JSON-LD Recipe block.
    Returns (title, servings, ingredients_list) or None if not found.
    """
    recipe = find_recipe_jsonld(soup)
    if not recipe:
        return None

    title   = str(recipe.get('name', '')).strip()
    servings = parse_servings(recipe.get('recipeYield', ''))
    raw_ings = recipe.get('recipeIngredient', [])

    if not raw_ings:
        return None

    ingredients = [
        normalize_fractions(re.sub(r'\s+', ' ', str(ing).strip()))
        for ing in raw_ings
        if str(ing).strip()
    ]
    return title, servings, ingredients


# ── Extraction strategy 2: WP Recipe Maker (WPRM) ────────────────────────────

def extract_wprm(soup):
    """
    Pull name, servings, and ingredient list using WPRM CSS selectors.
    Returns (title, servings, ingredients_list) or None if no WPRM block found.
    """
    title_tag = (
        soup.find('h2', class_='wprm-recipe-name')
        or soup.find('h1', class_='wprm-recipe-name')
        or soup.find('h1')
    )
    title = title_tag.get_text(' ', strip=True) if title_tag else ''

    serv_tag = soup.find('span', class_='wprm-recipe-servings')
    servings = serv_tag.get_text(strip=True) if serv_tag else ''
    if not servings:
        m = re.search(r'(\d+)\s+servings?', soup.get_text(), re.IGNORECASE)
        servings = m.group(1) if m else ''

    ingredients = []
    for li in soup.select('li.wprm-recipe-ingredient'):
        amount = li.find('span', class_='wprm-recipe-ingredient-amount')
        unit   = li.find('span', class_='wprm-recipe-ingredient-unit')
        name   = li.find('span', class_='wprm-recipe-ingredient-name')
        notes  = li.find('span', class_='wprm-recipe-ingredient-notes')

        amount_text = normalize_fractions(amount.get_text(strip=True)) if amount else ''
        unit_text   = unit.get_text(strip=True)  if unit   else ''
        name_text   = name.get_text(strip=True)  if name   else ''
        notes_text  = notes.get_text(strip=True) if notes  else ''

        if not name_text:
            continue
        parts = [p for p in [amount_text, unit_text, name_text, notes_text] if p]
        ingredients.append(' '.join(parts))

    if not ingredients:
        return None
    return title, servings, ingredients


# ── Main per-URL scrape function ──────────────────────────────────────────────

def scrape_one(recipe_id, recipe_name, url, session):
    """
    Fetch a single URL and extract recipe data using the appropriate strategy.
    Returns a result dict or None on failure.
    """
    source = classify_source(url)

    try:
        resp = session.get(url, timeout=30)
        if resp.status_code != 200:
            print(f'    HTTP {resp.status_code} — skipping')
            return None

        soup = BeautifulSoup(resp.text, 'lxml')

        result = None
        strategy_used = None

        # WPRM-first sources: africanbites, cheflola, zimbokitchen
        if source in ('africanbites', 'cheflola', 'zimbokitchen'):
            wprm = extract_wprm(soup)
            if wprm:
                result, strategy_used = wprm, 'wprm'
            else:
                jld = extract_jsonld(soup)
                if jld:
                    result, strategy_used = jld, 'jsonld-fallback'

        # JSON-LD-first sources: food.com, bbc, other
        else:
            jld = extract_jsonld(soup)
            if jld:
                result, strategy_used = jld, 'jsonld'
            elif source in ('africanbites', 'cheflola'):
                wprm = extract_wprm(soup)
                if wprm:
                    result, strategy_used = wprm, 'wprm-fallback'

        if not result:
            print(f'    No recipe data extracted — skipping')
            return None

        title, servings, ingredients = result
        # Fall back to the original recipe_name if the scrape returns nothing
        if not title:
            title = recipe_name

        return {
            'recipe_id'     : recipe_id,
            'recipe_name'   : title,
            'servings'      : servings,
            'ingredients'   : ' | '.join(ingredients),
            'source_url'    : url,
            'strategy_used' : strategy_used,
        }

    except Exception as exc:
        print(f'    Error: {exc}')
        return None


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    import pandas as pd
    df = pd.read_csv(INPUT_FILE, encoding='utf-8-sig')

    # Only rows with a URL
    to_scrape = df[df['recipe_url'].notna()].copy()
    skipped   = df[df['recipe_url'].isna()]

    print(f'Re-scraper — {len(to_scrape)} URLs to fetch  ({len(skipped)} skipped — no URL)')
    print('=' * 60)

    session = requests.Session()
    session.headers.update(HEADERS)

    results = []
    failed  = []

    for i, row in enumerate(to_scrape.itertuples(), start=1):
        source = classify_source(str(row.recipe_url))
        print(f'[{i:>2}/{len(to_scrape)}] [{source:<12}] {str(row.recipe_name)[:45]}')

        data = scrape_one(row.recipe_id, row.recipe_name, row.recipe_url, session)

        if data:
            n_ing = len(data['ingredients'].split(' | '))
            print(f'    OK  {n_ing} ingredients  (strategy: {data["strategy_used"]})')
            results.append(data)
        else:
            failed.append({'recipe_id': row.recipe_id, 'url': row.recipe_url})

        # Polite delay — 2 s between requests to avoid rate-limiting
        time.sleep(2)

    # ── Save results ──────────────────────────────────────────────────────────
    fieldnames = ['recipe_id', 'recipe_name', 'servings', 'ingredients',
                  'source_url', 'strategy_used']

    with open(OUTPUT_FILE, 'w', newline='', encoding='utf-8-sig') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)

    print()
    print('=' * 60)
    print(f'Successfully scraped : {len(results)} / {len(to_scrape)}')
    print(f'Failed               : {len(failed)}')
    print(f'No URL (skipped)     : {len(skipped)}')
    print(f'Output               : {OUTPUT_FILE}')

    if failed:
        with open(FAILED_FILE, 'w', encoding='utf-8') as f:
            for r in failed:
                f.write(f"{r['recipe_id']}\t{r['url']}\n")
        print(f'Failed list          : {FAILED_FILE}')


if __name__ == '__main__':
    main()
